name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_VERSION: 18

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Create Release

    needs:
      - test

    environment:
      name: release
      url: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}

    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    outputs:
      release-id: ${{ steps.changelog.outputs.release-id }}

    steps:
      - uses: actions/checkout@v3

      - name: Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}

  publish-npm:
    name: Publish to NPM

    needs:
      - release

    environment:
      name: npm
      url: https://www.npmjs.com/package/@foxify/router

    concurrency:
      group: ${{ github.workflow }}-npm-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci --no-fund

      - run: npm run build:hybrid

      - name: Publish the package
        run: npm publish --tag ${{ needs.release.outputs.release-id }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish to GitHub Packages

    needs:
      - release

    permissions:
      contents: read
      packages: write

    environment:
      name: gpr
      url: https://github.com/${{ github.repository }}/pkgs/npm/router

    concurrency:
      group: ${{ github.workflow }}-gpr-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: '@foxifyjs'

      - run: sed -i 's/@foxify\/router/@foxifyjs\/router/g' package.json package-lock.json

      - name: Install dependencies
        run: npm ci --no-fund

      - run: npm run build:hybrid

      - name: Publish the package
        run: npm publish --tag ${{ needs.release.outputs.release-id }}
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
